### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by DaddyWarbucks** [jaredhanson/passport-instagram#1]
How would I go about changing the auth scope to include likes, comments, and relationships?

Thanks for any help!

**Comment by gojohnnygo** [comment]
@DaddyWarbucks I would first read this: https://instagram.com/developer/authentication/#scope.

Then your implementation would look something like this: 

```
.get('/', passport.authenticate('instagram', {
    scope: ['comments', 'relationships'],
    failureRedirect: '/signup',
    session: false
}))
```

**Comment by contra** [comment]
@gojohnnygo @DaddyWarbucks Tried both `scopes` and `scope` as an array of scopes from instagram, neither work. Anyone actually get this working?

**Comment by gojohnnygo** [comment]
@contra code snippet?

**Comment by pm990320** [comment]
Having the same problem, set scope:["relationships"]  in the Strategy options, and as above, but still not working. Any updates?

**Comment by gojohnnygo** [comment]
@pm990320 What error are you getting? What endpoint are you trying to call specifically? Code snippet?

**Comment by robertu7** [comment]
+1

**Comment by robertu7** [comment]
@pm990320  @DaddyWarbucks https://instagram.com/developer/authentication/#scope
`All apps have basic read access by default, but if you plan on asking for extended access such as liking, commenting, or managing friendships, you need to specify these scopes in your authorization request. Note that in order to use these extended permissions, first you need to submit your app for review.`

see more: http://developers.instagram.com/post/116410697261/publishing-guidelines-and-signed-requests

**Comment by thierryskoda** [comment]
Has anyone found a solution for this? I tried   scope: ['comments', 'relationships'], and this doesn't work :(

**Comment by thierryskoda** [comment]
Never mind!! It works, I just didn't put the in the good function... I put it in the callback at the first time.. oups.
